import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    // API release artifacts are generated by `backend/package:release` and
    // already ignored by Git; lint the source tree instead.
    "backend/dist/**",
    "next-env.d.ts",
    // mobile/ is a separate Expo/React Native project with its own
    // tooling (see mobile/package.json) — not part of this Next.js app.
    "mobile/**",
  ]),
]);

export default eslintConfig;
