// AI question generation for the daily challenge — used by:
//  1. Admin "Сгенерировать сейчас через AI" button (creates/fills a challenge)
//  2. The question editor's "Заменить через AI 🔄" button (regenerates one question in place)
//  3. The AI Autopilot cron-equivalent path (called with autoGenerated: true)
//
// Requires SUPABASE_SERVICE_ROLE_KEY for the DB writes; the AI call itself
// goes through the shared lib/ai-gateway.ts (Groq by default).
import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { createAIGateway } from '@/lib/ai-gateway'
import { requireAdminApi } from '@/lib/api-auth'

function getAdminClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  )
}

const SUBJECTS = ['math', 'kyr', 'analogy', 'reading'] as const
type Subject = typeof SUBJECTS[number]

const SUBJECT_LABELS: Record<Subject, string> = {
  math: 'математика',
  kyr: 'кыргыз тили (грамматика)',
  analogy: 'аналогии / логика',
  reading: 'понимание прочитанного',
}

interface GeneratedQuestion {
  question_text: string
  subject: Subject
  section?: string
  topic?: string
  difficulty: 'easy' | 'medium' | 'hard'
  option_a: string
  option_b: string
  option_c: string
  option_d: string
  correct_answer: 'A' | 'B' | 'C' | 'D'
}

const MAX_SOURCE_CHARS = 6000

function buildPrompt(count: number, subjects: Subject[], difficulty: string, topic: string | null, sourceText: string | null) {
  const subjectList = subjects.map(s => `${s} (${SUBJECT_LABELS[s]})`).join(', ')
  const parts = [
    `Сгенерируй ровно ${count} вопросов с вариантами ответов для подготовки к ОРТ (Общереспубликанское тестирование, Кыргызстан).`,
    `Предметы для распределения вопросов: ${subjectList}. Распредели вопросы примерно поровну между этими предметами.`,
    `Сложность: ${difficulty === 'mixed' ? 'смешанная (easy/medium/hard вперемешку)' : difficulty}.`,
  ]
  if (topic) parts.push(`Тема: «${topic}». Все вопросы должны быть связаны с этой темой.`)
  if (sourceText) {
    parts.push(`Составь вопросы СТРОГО на основе следующего учебного материала:\n"""\n${sourceText.slice(0, MAX_SOURCE_CHARS)}\n"""`)
  }
  parts.push(
    'Ответь СТРОГО в формате JSON без markdown-обёртки, вида:',
    '{"questions":[{"question_text":"...","subject":"math","topic":"...","difficulty":"medium","option_a":"...","option_b":"...","option_c":"...","option_d":"...","correct_answer":"A"}]}',
    'Поле subject должно быть одним из: math, kyr, analogy, reading. Поле correct_answer — одна из букв A, B, C, D. Вопросы и варианты ответов — на русском языке.'
  )
  return parts.join('\n')
}

function sanitizeQuestion(raw: unknown): GeneratedQuestion | null {
  if (!raw || typeof raw !== 'object') return null
  const r = raw as Record<string, unknown>
  const subject = SUBJECTS.includes(r.subject as Subject) ? (r.subject as Subject) : null
  const letter = String(r.correct_answer ?? '').trim().toUpperCase().slice(0, 1)
  const correct = (['A', 'B', 'C', 'D'] as const).includes(letter as 'A' | 'B' | 'C' | 'D') ? (letter as 'A' | 'B' | 'C' | 'D') : null
  const difficulty = ['easy', 'medium', 'hard'].includes(r.difficulty as string) ? (r.difficulty as GeneratedQuestion['difficulty']) : 'medium'

  if (!subject || !correct || !r.question_text || !r.option_a || !r.option_b || !r.option_c || !r.option_d) return null

  return {
    question_text: String(r.question_text),
    subject,
    topic: r.topic ? String(r.topic) : undefined,
    difficulty,
    option_a: String(r.option_a),
    option_b: String(r.option_b),
    option_c: String(r.option_c),
    option_d: String(r.option_d),
    correct_answer: correct,
  }
}

async function generateQuestions(count: number, subjects: Subject[], difficulty: string, topic: string | null, sourceText: string | null): Promise<GeneratedQuestion[]> {
  const gateway = createAIGateway()
  const prompt = buildPrompt(count, subjects, difficulty, topic, sourceText)

  const raw = await gateway.complete(
    [
      { role: 'system', content: 'Ты — генератор тестовых вопросов для образовательной платформы. Всегда отвечай валидным JSON.' },
      { role: 'user', content: prompt },
    ],
    { type: 'plan', jsonMode: true }
  )

  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    // Some providers ignore jsonMode and wrap the payload in prose or a
    // ```json fence — fall back to extracting the first {...} block.
    const match = raw.match(/\{[\s\S]*\}/)
    if (!match) throw new Error('AI вернул невалидный JSON')
    parsed = JSON.parse(match[0])
  }

  const list = (parsed as { questions?: unknown[] })?.questions
  if (!Array.isArray(list)) throw new Error('AI не вернул список вопросов')

  const cleaned = list.map(sanitizeQuestion).filter((q): q is GeneratedQuestion => q !== null)
  if (cleaned.length === 0) throw new Error('AI не сгенерировал ни одного валидного вопроса')
  return cleaned
}

export async function POST(req: NextRequest) {
  const authError = await requireAdminApi(req)
  if (authError) return authError

  try {
    const body = await req.json()
    const {
      challengeId, replaceQuestionId, count, subjects, difficulty, topic, sourceText, saveToBank,
    } = body as {
      challengeId?: string
      replaceQuestionId?: string
      count?: number
      subjects?: Subject[]
      difficulty?: string
      topic?: string | null
      sourceText?: string | null
      saveToBank?: boolean
    }

    const supabaseAdmin = getAdminClient()

    // Mode 1: replace a single existing question in place.
    if (replaceQuestionId) {
      const { data: existing } = await supabaseAdmin
        .from('daily_challenge_questions')
        .select('subject, topic, difficulty')
        .eq('id', replaceQuestionId)
        .maybeSingle()

      const targetSubjects: Subject[] = existing?.subject ? [existing.subject as Subject] : ['math']
      const [generated] = await generateQuestions(1, targetSubjects, existing?.difficulty ?? 'medium', existing?.topic ?? topic ?? null, sourceText ?? null)

      const { error } = await supabaseAdmin
        .from('daily_challenge_questions')
        .update({ ...generated, ai_generated: true })
        .eq('id', replaceQuestionId)
      if (error) return NextResponse.json({ error: error.message }, { status: 400 })

      return NextResponse.json({ success: true })
    }

    const finalCount = count ?? 17
    const finalSubjects = subjects && subjects.length > 0 ? subjects : [...SUBJECTS]
    const questions = await generateQuestions(finalCount, finalSubjects, difficulty ?? 'medium', topic ?? null, sourceText ?? null)

    // Mode 2: generate straight into a specific (existing) challenge.
    if (challengeId) {
      const { data: existingRows } = await supabaseAdmin
        .from('daily_challenge_questions')
        .select('order_num')
        .eq('challenge_id', challengeId)
        .order('order_num', { ascending: false })
        .limit(1)
      let nextOrder = (existingRows?.[0]?.order_num ?? 0) + 1

      const rows = questions.map(q => ({ challenge_id: challengeId, ...q, ai_generated: true, order_num: nextOrder++ }))
      const { error } = await supabaseAdmin.from('daily_challenge_questions').insert(rows)
      if (error) return NextResponse.json({ error: error.message }, { status: 400 })

      return NextResponse.json({ success: true, count: rows.length })
    }

    // Mode 3: no challenge — save straight to the standalone bank
    // (challenge_id null), e.g. from the knowledge-base pipeline.
    if (saveToBank) {
      const rows = questions.map((q, i) => ({ challenge_id: null, ...q, ai_generated: true, order_num: i + 1 }))
      const { error } = await supabaseAdmin.from('daily_challenge_questions').insert(rows)
      if (error) return NextResponse.json({ error: error.message }, { status: 400 })
      return NextResponse.json({ success: true, count: rows.length })
    }

    return NextResponse.json({ questions })
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Неизвестная ошибка генерации'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
