// Requires SUPABASE_SERVICE_ROLE_KEY (server-only env var) — same
// service-role write pattern as the other /api/admin/* routes (see
// app/api/admin/questions/route.ts) rather than writing via the anon client.
import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { requireAdminApi } from '@/lib/api-auth'

function getAdminClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  )
}

export async function POST(req: NextRequest) {
  const authError = await requireAdminApi(req)
  if (authError) return authError

  try {
    const supabaseAdmin = getAdminClient()
    const { title, date, questionCount, xpReward, status, autoGenerated } = await req.json()
    if (!title || !date) return NextResponse.json({ error: 'title и date обязательны' }, { status: 400 })

    const { data, error } = await supabaseAdmin
      .from('daily_challenges')
      .insert({
        title,
        date,
        question_count: questionCount ?? 17,
        xp_reward: xpReward ?? 80,
        status: status ?? 'draft',
        auto_generated: !!autoGenerated,
      })
      .select('id')
      .single()
    if (error || !data) return NextResponse.json({ error: error?.message ?? 'Не удалось создать задание' }, { status: 400 })

    return NextResponse.json({ id: data.id })
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Неизвестная ошибка'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}

export async function PATCH(req: NextRequest) {
  const authError = await requireAdminApi(req)
  if (authError) return authError

  try {
    const supabaseAdmin = getAdminClient()
    const body = await req.json()
    const { id } = body
    if (!id) return NextResponse.json({ error: 'id обязателен' }, { status: 400 })

    const update: Record<string, unknown> = {}
    if (body.title !== undefined) update.title = body.title
    if (body.date !== undefined) update.date = body.date
    if (body.questionCount !== undefined) update.question_count = body.questionCount
    if (body.xpReward !== undefined) update.xp_reward = body.xpReward
    if (body.status !== undefined) {
      update.status = body.status
      if (body.status === 'published') update.published_at = new Date().toISOString()
    }

    const { error } = await supabaseAdmin.from('daily_challenges').update(update).eq('id', id)
    if (error) return NextResponse.json({ error: error.message }, { status: 400 })

    return NextResponse.json({ success: true })
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Неизвестная ошибка'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}

export async function DELETE(req: NextRequest) {
  const authError = await requireAdminApi(req)
  if (authError) return authError

  try {
    const supabaseAdmin = getAdminClient()
    const { id } = await req.json()
    if (!id) return NextResponse.json({ error: 'id обязателен' }, { status: 400 })

    const { error } = await supabaseAdmin.from('daily_challenges').delete().eq('id', id)
    if (error) return NextResponse.json({ error: error.message }, { status: 400 })

    return NextResponse.json({ success: true })
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Неизвестная ошибка'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
